name: Generate WebP Thumbnails

on:
  push:
    branches: [ main ]
    paths:
      - '**.webp'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
  workflow_dispatch:

jobs:
  build-thumbnails:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install ImageMagick (for `magick mogrify`)
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      # 3️⃣ Prepare th
